/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.37
 * Generated at: 2022-01-26 08:22:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.boardsearch;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>아코디언게시판</title>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"../css/public.css\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css\">\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"></script>\r\n");
      out.write("  <script src=\"../js/jquery-3.6.0.min.js\"></script>\r\n");
      out.write("  \r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js\"></script>\r\n");
      out.write("  <script src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"../js/board.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("body{\r\n");
      out.write("\tpadding : 20px;\r\n");
      out.write("}\r\n");
      out.write(".box{\r\n");
      out.write("\tpadding : 20px;\r\n");
      out.write("}\r\n");
      out.write(".card{\r\n");
      out.write("\tmargin : 2px;\r\n");
      out.write("}\r\n");
      out.write(".card-header{\r\n");
      out.write("\tbackground: #32AAFF;\r\n");
      out.write("}\r\n");
      out.write(".card-header:hover{\r\n");
      out.write("\tbackground: lightblue;\r\n");
      out.write("}\r\n");
      out.write(".card-link{\r\n");
      out.write("\tcolor : black;\r\n");
      out.write("}\r\n");
      out.write(".pagination{\r\n");
      out.write("\tfloat:left;\r\n");
      out.write("}\r\n");
      out.write("#btngroup1{\r\n");
      out.write("\tmargin-left : 42%; \r\n");
      out.write("}\r\n");
      out.write("input[name=reply]{\r\n");
      out.write("\theight: 55px;\r\n");
      out.write("\tvertical-align : top;\r\n");
      out.write("}\r\n");
      out.write(".navbar{\r\n");
      out.write("\tbackground: lightblue;\r\n");
      out.write("}\r\n");
      out.write("#stype{\r\n");
      out.write("\twidth : 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script>\r\n");
      out.write("$(function(){\r\n");
      out.write("\tlistServer(1);\r\n");
      out.write("\t\r\n");
      out.write("\t//이벤트\r\n");
      out.write("\t//수정, 삭제, 등록 버튼에 대한 이벤트\r\n");
      out.write("\t$('.box').on('click', '.action', function(){\r\n");
      out.write("\t\tactionName = $(this).attr('name');\r\n");
      out.write("\t\tactionIdx = $(this).attr('idx');\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif(actionName == \"modify\"){\r\n");
      out.write("\t\t\talert(actionIdx + \"번 글을 수정합니다\")\r\n");
      out.write("\t\t}else if(actionName == \"delete\"){\r\n");
      out.write("\t\t\talert(actionIdx + \"번 글을 삭제합니다\")\r\n");
      out.write("\t\t}else if(actionName == \"reply\"){\r\n");
      out.write("\t\t\talert(actionIdx + \"번 글에 댓글을 답니다\")\r\n");
      out.write("\t\t}\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t// page번호 - pnum 이벤트\r\n");
      out.write("\t$('#btngroup1').on('click', '.pnum', function(){\r\n");
      out.write("\t\tnumtext = $(this).text().trim();\r\n");
      out.write("\t\tcurrentPage = numtext;\r\n");
      out.write("\t\tlistServer(currentPage);\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$('#btngroup1').on('click', '.next', function(){\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tnextnum = parseInt($('.pager a').last().text().trim())+1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcurrentPage = nextnum;\r\n");
      out.write("\t\tlistServer(currentPage);\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t$('#btngroup1').on('click', '.previous', function(){\r\n");
      out.write("\t\tprevnum = parseInt($('.pager a').first().text().trim())-1;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tcurrentPage = prevnum;\r\n");
      out.write("\t\tlistServer(currentPage);\r\n");
      out.write("\t})\r\n");
      out.write("\t\r\n");
      out.write("\t\r\n");
      out.write("})\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("<br>\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("<nav class=\"navbar navbar-expand-sm\">\r\n");
      out.write("\t<select id=\"stype\" class=\"form-control\">\r\n");
      out.write("\t<option value=\"\">전체</option>\r\n");
      out.write("\t<option value=\"writer\">이름</option>\r\n");
      out.write("\t<option value=\"subject\">제목</option>\r\n");
      out.write("\t<option value=\"content\">내용</option>\r\n");
      out.write("\t</select>\r\n");
      out.write("  <form class=\"form-inline\">\r\n");
      out.write("    <input id=\"sword\" class=\"form-control mr-sm-2\" type=\"text\" placeholder=\"Search\">\r\n");
      out.write("    <button class=\"btn btn-success\" type=\"button\">Search</button>\r\n");
      out.write("  </form>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div class=\"box\">\r\n");
      out.write("</div>\r\n");
      out.write("<br><br>\r\n");
      out.write("<div id=\"btngroup1\">\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
